export const THEMES = [
{
id: 'espresso',
name: 'Espresso',
color: '#1c1917',
vars: {
    '--bg-main': '#1c1917',
    '--bg-surface': '#26221f',
    '--bg-surface-hover': '#332e29',
    '--border-subtle': '#38322c',
    '--text-primary': '#f5f2eb',
    '--text-secondary': '#a89f91',
    '--accent-warm': '#c88346',
},
},
{
id: 'warm-cream',
name: 'Warm Cream',
color: '#f5f2eb',
vars: {
    '--bg-main': '#f5f2eb',
    '--bg-surface': '#ffffff',
    '--bg-surface-hover': '#ebd6c1',
    '--border-subtle': '#e5e0d8',
    '--text-primary': '#1a1918',
    '--text-secondary': '#666059',
    '--accent-warm': '#c88346',
},
},
{
id: 'blue-dark',
name: 'Ocean Dark',
color: '#0f172a',
vars: {
    '--bg-main': '#0f172a',
    '--bg-surface': '#1e293b',
    '--bg-surface-hover': '#334155',
    '--border-subtle': '#334155',
    '--text-primary': '#f8fafc',
    '--text-secondary': '#94a3b8',
    '--accent-warm': '#38bdf8',
},
},
{
id: 'ocean',
name: 'Ocean Light',
color: '#e0f2fe',
vars: {
    '--bg-main': '#f0f9ff',
    '--bg-surface': '#ffffff',
    '--bg-surface-hover': '#e0f2fe',
    '--border-subtle': '#bae6fd',
    '--text-primary': '#0c4a6e',
    '--text-secondary': '#0284c7',
    '--accent-warm': '#0284c7',
},
},
{
id: 'pink',
name: 'Pink Glam',
color: '#ec4899',
vars: {
    '--bg-main': '#fdf2f8',
    '--bg-surface': '#ffffff',
    '--bg-surface-hover': '#fce7f3',
    '--border-subtle': '#fbcfe8',
    '--text-primary': '#831843',
    '--text-secondary': '#db2777',
    '--accent-warm': '#ec4899',
},
},
{
id: 'pink-dark',
name: 'Magenta Noir',
color: '#db2777',
vars: {
    '--bg-main': '#18040f',
    '--bg-surface': '#280a1c',
    '--bg-surface-hover': '#3d122b',
    '--border-subtle': '#581c3e',
    '--text-primary': '#fdf2f8',
    '--text-secondary': '#f472b6',
    '--accent-warm': '#f472b6',
},
},
{
id: 'emerald',
name: 'Emerald',
color: '#064e3b',
vars: {
    '--bg-main': '#022c22',
    '--bg-surface': '#064e3b',
    '--bg-surface-hover': '#047857',
    '--border-subtle': '#065f46',
    '--text-primary': '#ecfdf5',
    '--text-secondary': '#6ee7b7',
    '--accent-warm': '#34d399',
},
},
{
id: 'sage',
name: 'Sage Green',
color: '#a3b18a', 
variables: {
    '--bg-main': '#f4f7f4',
    '--bg-surface': '#e8efe8',
    '--bg-surface-hover': '#dde7dd',
    '--border-subtle': '#cbd5cb',
    '--text-primary': '#1c281d',
    '--text-secondary': '#4a5d4c',
    '--accent-warm': '#588157',
},
},
{
id: 'gray',
name: 'Slate Gray',
color: '#374151',
vars: {
    '--bg-main': '#111827',
    '--bg-surface': '#1f2937',
    '--bg-surface-hover': '#374151',
    '--border-subtle': '#4b5563',
    '--text-primary': '#f9fafb',
    '--text-secondary': '#9ca3af',
    '--accent-warm': '#9ca3af',
},
},
{
id: 'pitch-dark',
name: 'Pitch Dark',
color: '#000000',
vars: {
    '--bg-main': '#050505',
    '--bg-surface': '#121212',
    '--bg-surface-hover': '#1e1e1e',
    '--border-subtle': '#27272a',
    '--text-primary': '#ffffff',
    '--text-secondary': '#a1a1aa',
    '--accent-warm': '#e4e4e7',
},
},
{
id: 'midnight-purple',
name: 'Midnight Purple',
color: '#3b0764',
vars: {
    '--bg-main': '#0f051d',
    '--bg-surface': '#1c0b36',
    '--bg-surface-hover': '#2a124d',
    '--border-subtle': '#4c1d95',
    '--text-primary': '#f3e8ff',
    '--text-secondary': '#c084fc',
    '--accent-warm': '#a855f7',
},
},
{
id: 'storm-vanilla',
name: 'Storm & Vanilla',
color: '#537179',
vars: {
    '--bg-main': '#1b2426',
    '--bg-surface': '#263337',
    '--bg-surface-hover': '#35454a',
    '--border-subtle': '#3f5258',
    '--text-primary': '#f4efe8',
    '--text-secondary': '#bfae99',
    '--accent-warm': '#bfae99',
},
},
{
id: 'raspberry-sky',
name: 'Raspberry Velvet',
color: '#7b3b4b',
vars: {
    '--bg-main': '#190a0f',
    '--bg-surface': '#2b131a',
    '--bg-surface-hover': '#3d1b25',
    '--border-subtle': '#522532',
    '--text-primary': '#f2f7f8',
    '--text-secondary': '#a8bbbf',
    '--accent-warm': '#a8bbbf',
},
},
{
id: 'sage-olive',
name: 'Sage & Olive',
color: '#3b3c36',
vars: {
    '--bg-main': '#1c1d1a',
    '--bg-surface': '#292a25',
    '--bg-surface-hover': '#3b3c36',
    '--border-subtle': '#484a43',
    '--text-primary': '#f2f3ef',
    '--text-secondary': '#b2b59c',
    '--accent-warm': '#b2b59c',
},
},
];

export const DEFAULT_THEME_ID = 'espresso';

export function getThemeById(id) {
return THEMES.find((t) => t.id === id) || THEMES[0];
}